 CREATE TABLE `CsJRuhA9v6`.`PIZZAS` 
 ( `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NOT NULL ,
 `TMSTAMP` DATETIME DEFAULT CURRENT_TIMESTAMP ,
 PRIMARY KEY (`ID`));

  CREATE TABLE `CsJRuhA9v6`.`PIZZASHOPS` 
 ( `ID` INT NOT NULL AUTO_INCREMENT,
  `PLACEID` VARCHAR(200) NOT NULL,
  `NAME` VARCHAR(100) NOT NULL ,
 `TMSTAMP` DATETIME DEFAULT CURRENT_TIMESTAMP ,
 PRIMARY KEY (`ID`));

  CREATE TABLE `CsJRuhA9v6`.`RELATEPIZZASHOPSPIZZAS` 
 ( `ID` INT NOT NULL AUTO_INCREMENT,
  `SHOPID` INT NOT NULL,
  `PIZZAID` INT NOT NULL ,
 `TMSTAMP` DATETIME DEFAULT CURRENT_TIMESTAMP ,
 PRIMARY KEY (`ID`),
 FOREIGN KEY (`SHOPID`) REFERENCES PIZZASHOPS(ID),
 FOREIGN KEY (`PIZZAID`) REFERENCES PIZZAS(ID)
  );

 CREATE TABLE `CsJRuhA9v6`.`REVIEWS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `USERID` VARCHAR(100) NOT NULL,
  `TOPIC` int(11) NOT NULL,
  `REVIEW` blob NOT NULL,
  `RATING` decimal(10,0) NOT NULL DEFAULT '-1',
  `TMSTAMP` datetime DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (`ID`),
 FOREIGN KEY (`TOPIC`) REFERENCES RELATEPIZZASHOPSPIZZAS(ID)
)
